package main.java;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bron2
 */

import java.sql.*;
import javax.swing.*;

public class ProductsAddButtonFrame extends javax.swing.JFrame {

    /**
     * Creates new form addFrame
     */
    public ProductsAddButtonFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topMessageLabel = new javax.swing.JLabel();
        jPanelFormBody = new javax.swing.JPanel();
        productNameTextField = new javax.swing.JTextField();
        categoryTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        stockQuantityTextField = new javax.swing.JTextField();
        stockAlertTextField = new javax.swing.JTextField();
        descriptionTextField = new javax.swing.JTextField();
        imageTextField = new javax.swing.JTextField();
        productNameLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        stockQuantityLabel = new javax.swing.JLabel();
        stockAlertLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        addRecordButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a Product");

        topMessageLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        topMessageLabel.setText("Please fill out the boxes below to add a product.");

        priceTextField.setText("$0.00");

        stockQuantityTextField.setText("0");

        stockAlertTextField.setText("5");

        productNameLabel.setText("Product Name:");

        categoryLabel.setText("Category:");

        priceLabel.setText("Price:");

        stockQuantityLabel.setText("Stock Quantity:");

        stockAlertLabel.setText("Stock Alert Level:");

        descriptionLabel.setText("Description:");

        imageLabel.setText("Image URL:");

        javax.swing.GroupLayout jPanelFormBodyLayout = new javax.swing.GroupLayout(jPanelFormBody);
        jPanelFormBody.setLayout(jPanelFormBodyLayout);
        jPanelFormBodyLayout.setHorizontalGroup(
            jPanelFormBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productNameLabel)
                    .addComponent(categoryLabel)
                    .addComponent(priceLabel)
                    .addComponent(stockQuantityLabel)
                    .addComponent(stockAlertLabel)
                    .addComponent(descriptionLabel)
                    .addComponent(imageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imageTextField)
                    .addComponent(productNameTextField)
                    .addComponent(stockAlertTextField)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(stockQuantityTextField)
                    .addComponent(priceTextField)
                    .addComponent(categoryTextField))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanelFormBodyLayout.setVerticalGroup(
            jPanelFormBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormBodyLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanelFormBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockQuantityLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockAlertTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockAlertLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageLabel))
                .addGap(18, 18, 18))
        );

        addRecordButton.setBackground(new java.awt.Color(153, 220, 255));
        addRecordButton.setText("Add to Stock");
        addRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecordButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(addRecordButton)
                .addGap(49, 49, 49)
                .addComponent(cancelButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRecordButton)
                    .addComponent(cancelButton))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFormBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(topMessageLabel)
                        .addGap(177, 177, 177)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(topMessageLabel)
                .addGap(31, 31, 31)
                .addComponent(jPanelFormBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose(); //closes the addButtonFrame window when cancelled
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    //adds record to the DB
    private void addRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecordButtonActionPerformed
        // TODO add your handling code here:
        
        //adds the textFields data to variables for user validation, then SQL input following
        String name = productNameTextField.getText().strip();
        String category = categoryTextField.getText().strip();
        String priceText = priceTextField.getText().strip();
        String quantityText = stockQuantityTextField.getText().strip();
        String stockAlertText = stockAlertTextField.getText().strip();
        String description = descriptionTextField.getText().strip();
        String imageUrl = imageTextField.getText().strip();
        
        
        // USER VALIDATION - if user leaves empty boxes. except imageURL and description
        if ( name.isEmpty() || category.isEmpty() ||  priceText.isEmpty() || quantityText.isEmpty() || stockAlertText.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Error: All boxes except Description and Image URL must be filled.");
            return;
        }
        
        // remove dollar sign from price
        priceText = priceText.replace("$", "");
        
        // USER VALIDATION - check price if NOT a double, error message
        if ( !MainWindow.isADouble(priceText) ) {
            JOptionPane.showMessageDialog(this, "Error: price must be a valid decimal value.");
            return;
        }
        
        // if price is double change to double data type
        double price = Double.parseDouble(priceText);
        
        
        // USER VALIDATION - check quantity and stock Alert for being an integer
        if ( !MainWindow.isAnInteger(quantityText) || !MainWindow.isAnInteger(stockAlertText) ) {
            JOptionPane.showMessageDialog(this, "Error: Stock Quantity and Stock Alert Level must have valid whole number values.");
            return;
        }
        
        // if quantity and stock alert are whole numbers change to int data type
        int quantity = Integer.parseInt(quantityText);
        int stockAlert = Integer.parseInt(stockAlertText);
        
        // check if price, quantity, and stockAlert are <= 0, if so then display error
        if ( price <= 0 || quantity <= 0 || stockAlert <= 0) {
            JOptionPane.showMessageDialog(this, "Error: Price, Stock Quantity, and Stock Alert Level must be values greater than zero.");
            return;
        }
        
        //SQL command
        String insertSQL = "INSERT INTO products (name, category, price, stock_quantity, low_stock_threshold, description, image_url) "
                            + "VALUES (?, ?, ?, ?, ?, ?, ?)"; // <<---- ? used to prevent SQL injections
        
        
         try (Connection conn = DatabaseUtil.getConnection(); //my shared connection
         PreparedStatement stmt = conn.prepareStatement(insertSQL)) { //creates prepared statement obj for assigning

        //sets the values for the prepared statement from the corresponding variable
        stmt.setString(1, name);
        stmt.setString(2, category);
        stmt.setDouble(3, price);
        stmt.setInt(4, quantity);
        stmt.setInt(5, stockAlert);
        stmt.setString(6, description);
        stmt.setString(7, imageUrl);

        // Execute the insert statement
        int rowsAffected = stmt.executeUpdate();

        // Provide feedback based on success
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Product added successfully! Please refresh.");
            System.out.println("Product added successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add product.");
            System.out.println("Failed to add product.");
        }
        } catch (SQLException e) {
            // Handle potential database connection or SQL errors
            e.printStackTrace(); //for debugging
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        
        // close the window
        this.dispose();
        
    }//GEN-LAST:event_addRecordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsAddButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsAddButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsAddButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsAddButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductsAddButtonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRecordButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField imageTextField;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelFormBody;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JTextField productNameTextField;
    private javax.swing.JLabel stockAlertLabel;
    private javax.swing.JTextField stockAlertTextField;
    private javax.swing.JLabel stockQuantityLabel;
    private javax.swing.JTextField stockQuantityTextField;
    private javax.swing.JLabel topMessageLabel;
    // End of variables declaration//GEN-END:variables
}
