package main.java;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bron2
 */
public class SalesEditButtonFrame extends javax.swing.JFrame {
    
    // global class attributes for querying and updating the DB
    private int saleItemId; 
    private int productId;
    private int quantitySold;
    private double saleSubtotal;
    
    public SalesEditButtonFrame(String productId, String quantitySold, String saleItemId, String saleSubtotal) {
        initComponents();
        
        this.saleItemId = Integer.parseInt(saleItemId);
        this.productId = Integer.parseInt(productId);
        this.quantitySold = Integer.parseInt(quantitySold);
        this.saleSubtotal = Double.parseDouble(saleSubtotal.replaceAll("[^0-9.]", ""));
        
        productIdTextField.setText(productId);
        quantityTextField.setText(quantitySold);
    }
    
    public SalesEditButtonFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        instructionLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        productIdTextField = new javax.swing.JTextField();
        quantityTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        productIdLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit a Sale");

        instructionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        instructionLabel.setText("Please fill out the boxes below to edit the sale item.");

        submitButton.setBackground(new java.awt.Color(153, 220, 255));
        submitButton.setText("Submit Changes");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        productIdLabel.setText("Product ID:");

        quantityLabel.setText("Quantity:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productIdLabel)
                    .addComponent(quantityLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(quantityTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(submitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productIdLabel)
                    .addComponent(productIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(instructionLabel)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(instructionLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        
        // USER VALIDATION  - var to store bool for calling isAnInteger() method
        boolean isProductIdInt = MainWindow.isAnInteger(productIdTextField.getText());
        boolean isQuantityInt = MainWindow.isAnInteger(quantityTextField.getText());
        
        // USER VALIDATION  - checks if Int values
        if (isProductIdInt == false || isQuantityInt == false) {
            JOptionPane.showMessageDialog(this, "Invalid Entry: Values must be numerical, contain no decimals, and be greater than 0.");
            return;
        }
       
        // get the user's new entries
        int newProductId = Integer.parseInt(productIdTextField.getText());
        int newQuantity = Integer.parseInt(quantityTextField.getText());
        
        // USER VALIDATION - checks if value is 0 or less
        if (newProductId <= 0 || newQuantity <= 0) {
            JOptionPane.showMessageDialog(this, "Invalid Entry: Values must be greater than 0.");
            return;
        }
        
        // ------ DB QUERY SECTION ------ edit the values and perform calculations for DB

        try (Connection conn = DatabaseUtil.getConnection()) {
            conn.setAutoCommit(false);  // Start transaction

        // Restore old product to stock -> this.quantitySold + Products.quantity
            try (PreparedStatement stmt = conn.prepareStatement(
                    "UPDATE products SET products.stock_quantity = products.stock_quantity + ? WHERE product_id = ?")) {
                stmt.setInt(1, this.quantitySold);
                stmt.setInt(2, this.productId);
                stmt.executeUpdate();
            }

        // Subtract old subtotal from Sales.total_amount -> total_amount - this.saleSubtotal
            try (PreparedStatement stmt = conn.prepareStatement(
                    "UPDATE sales SET total_amount = total_amount - ? WHERE sale_id = (SELECT sale_id FROM salesitems WHERE sale_item_id = ?)")) {
                stmt.setDouble(1, this.saleSubtotal);
                stmt.setInt(2, this.saleItemId);
                stmt.executeUpdate();
            }

        // Update SalesItems record with the new user entries
            try (PreparedStatement stmt = conn.prepareStatement(
                    "UPDATE salesitems SET product_id = ?, quantity = ? WHERE sale_item_id = ?")) {
                stmt.setInt(1, newProductId);
                stmt.setInt(2, newQuantity);
                stmt.setInt(3, this.saleItemId);
                stmt.executeUpdate();
            }

        // Subtract new quantity from new product's current stock
            try (PreparedStatement stmt = conn.prepareStatement(
                    "UPDATE products SET stock_quantity = stock_quantity - ? WHERE product_id = ?")) {
                stmt.setInt(1, newQuantity);
                stmt.setInt(2, newProductId);
                stmt.executeUpdate();
            }

        // Get new unit price
            double newUnitPrice; // var to hold new price
            try (PreparedStatement stmt = conn.prepareStatement(
                    "SELECT price FROM products WHERE product_id = ?")) {
                stmt.setInt(1, newProductId);
                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    newUnitPrice = rs.getDouble("price");
                } else {
                    throw new SQLException("New product not found.");
                }
            }

        // get the new subtotal to Sales.total_amount
            double newSubtotal = newUnitPrice * newQuantity;
            try (PreparedStatement stmt = conn.prepareStatement(
                    "UPDATE sales SET total_amount = total_amount + ? WHERE sale_id = (SELECT sale_id FROM salesitems WHERE sale_item_id = ?)")) {
                stmt.setDouble(1, newSubtotal);
                stmt.setInt(2, this.saleItemId);
                stmt.executeUpdate();
            }

            conn.commit(); // Commit to the DB
            JOptionPane.showMessageDialog(this, "Sale item updated successfully. Please refresh.");
            this.dispose();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }   
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesEditButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesEditButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesEditButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesEditButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesEditButtonFrame().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel productIdLabel;
    private javax.swing.JTextField productIdTextField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
